plugins {
    id 'java-library'
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '[6.0.24,6.2)'
    id 'org.spongepowered.mixin' version '0.7.+'
}

version = "${mod_version}+mc${minecraft_version}"
group = mod_group_id

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.withType(ProcessResources).configureEach {
    filteringCharset = 'UTF-8'
}

minecraft {
    mappings channel: mapping_channel, version: mapping_version

    copyIdeResources = true

    runs {
        configureEach {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
        }

        client {
            property 'forge.enabledGameTestNamespaces', mod_id
            mods {
                "${mod_id}" {
                    source sourceSets.main
                }
            }
        }

        server {
            property 'forge.enabledGameTestNamespaces', mod_id
            args '--nogui'
            mods {
                "${mod_id}" {
                    source sourceSets.main
                }
            }
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

mixin {
    add sourceSets.main, "${mod_id}.refmap.json"
    config "${mod_id}.mixins.json"
}

repositories {
    mavenLocal()
    maven { url = 'https://maven.neoforged.net/releases' }
}

dependencies {
    minecraft "net.neoforged:forge:${minecraft_version}-${neo_version}"
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
}

processResources {
    var replaceProperties = [minecraft_version_range: minecraft_version_range,
                             forge_version_range    : forge_version_range,
                             loader_version_range   : loader_version_range,
                             mod_id                 : mod_id,
                             mod_name               : mod_name,
                             mod_license            : mod_license,
                             mod_version            : project.version,
                             mod_authors            : mod_authors,
                             mod_description        : new String(
                                     mod_description.getBytes('ISO-8859-1'), 'UTF-8')]
    inputs.properties replaceProperties
    filesMatching('META-INF/mods.toml') {
        expand replaceProperties
    }
}

tasks.named('jar') {
    archiveClassifier = 'neoforge'
    finalizedBy 'reobfJar'

    manifest {
        attributes([
                'MixinConfigs'   : "${mod_id}.mixins.json",
                'Specification-Title'   : mod_id,
                'Specification-Version' : '1',
                'Implementation-Title'  : mod_name,
                'Implementation-Version': project.version
        ])
    }
}
